Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2018-03, with the labels that each got.

#314 Minor modifications to MPAS-Seaice documentation
  docs/mpasseaice.rst
Labels: clean up

#312 Optionally add bolus velocity to MOC
  configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil
  mpas_analysis/config.default
  mpas_analysis/ocean/streamfunction_moc.py
Labels: enhancement, priority

#317 Add support for specifying the anomaly ref year
  mpas_analysis/config.default
  mpas_analysis/ocean/compute_anomaly_subtask.py
  mpas_analysis/shared/time_series/anomaly.py
  mpas_analysis/shared/time_series/mpas_time_series_task.py
Labels: enhancement

#319 Fix encoding headers in python files
  licenses/_headers/license-bump-copyright.sh
  licenses/_headers/license-find-missing.sh
  licenses/_headers/license-prepend-missing.sh
  licenses/_headers/license-setup.sh
  mpas_analysis/ocean/climatology_map_argo.py
  mpas_analysis/ocean/compute_anomaly_subtask.py
  mpas_analysis/ocean/index_nino34.py
  mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py
  mpas_analysis/ocean/plot_hovmoller_subtask.py
  mpas_analysis/ocean/streamfunction_moc.py
  mpas_analysis/ocean/time_series_ohc_anomaly.py
  mpas_analysis/ocean/time_series_salinity_anomaly.py
  mpas_analysis/ocean/time_series_temperature_anomaly.py
  mpas_analysis/shared/time_series/anomaly.py
  mpas_analysis/shared/time_series/moving_average.py
  run_mpas_analysis
Labels: bug, priority
