Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2018-11, with the labels that each got.

#462 Update the location, depth and seasons for SOSE transects
  README.md
  conda/recipe/meta.yaml
  mpas_analysis/config.default
  mpas_analysis/ocean/sose_transects.py
  mpas_analysis/shared/plot/plotting.py
Labels: bug, clean up, enhancement

#471 Add climatologyMapBGC to docs
  docs/analysis_tasks.rst
  docs/design_docs/eddykineticenergy.md
  docs/tasks/climatologyMapBGC.rst
  mpas_analysis/config.default
Labels: clean up, documenation

#472 Switch to m2r instead of recommonmark
  README.md
  docs/api.rst
  docs/conf.py
  docs/design_docs/analysis_task_template.md
  docs/design_docs/config_file_reorganization.md
  docs/design_docs/parallel_tasks.md
  docs/design_docs/variable_mapping_reorg.md
  docs/environment.yml
  docs/index.rst
  docs/parse_quick_start.py
Labels: bug, documenation

#475 Fix detecting periodic lat/lon descriptors
  mpas_analysis/shared/grid/grid.py
Labels: bug, enhancement

#478 Fix CI under python 2
  mpas_analysis/test/test_mpas_config_parser.py
  mpas_analysis/test/test_mpas_xarray.py
  mpas_analysis/test/test_timekeeping.py
Labels: bug

#473 Explicitly set colormap type (indexed or continuous) in config options
  mpas_analysis/config.default
  mpas_analysis/shared/plot/plotting.py
Labels: bug

#486 Add periodic image to BGC obs data
  mpas_analysis/obs/analysis_input_files
  mpas_analysis/ocean/climatology_map_bgc.py
  mpas_analysis/shared/interpolation/utility.py
Labels: bug

#482 Add a subtask for computing region masks on the fly
  README.md
  ci/requirements.yml
  conda/recipe/meta.yaml
  docs/api.rst
  mpas_analysis/__main__.py
  mpas_analysis/config.default
  mpas_analysis/obs/analysis_input_files
  mpas_analysis/ocean/time_series_antarctic_melt.py
  mpas_analysis/shared/html/pages.py
  mpas_analysis/shared/regions/__init__.py
  mpas_analysis/shared/regions/compute_region_masks_subtask.py
Labels: enhancement

#489 Enhance "error bars" for observations in Antarctic melt time series plots
  mpas_analysis/ocean/time_series_antarctic_melt.py
  mpas_analysis/shared/plot/plotting.py
Labels: bug, enhancement, priority

#491 Catches zero arguments
  mpas_analysis/__main__.py
Labels: bug

#487 Break the MOC into several subtasks
  mpas_analysis/__main__.py
  mpas_analysis/config.default
  mpas_analysis/ocean/streamfunction_moc.py
  mpas_analysis/shared/analysis_task.py
  mpas_analysis/shared/climatology/mpas_climatology_task.py
  mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py
  mpas_analysis/shared/time_series/mpas_time_series_task.py
  mpas_analysis/test/test_mpas_climatology_task.py
Labels: enhancement, priority

#485 Clean up before v1.1 release
  configs/acme1/config.20180129.DECKv1b_piControl.ne30_oEC.edison
  configs/alcf/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta
  configs/alcf/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta
  configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil
  configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl
  configs/edison/config.20180129.DECKv1b_piControl.ne30_oEC.edison
  configs/edison/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix
  configs/edison/config.20180514.G.oQU240wLI.edison
  configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison
  configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf
  configs/lanl/config.MatchBoth_orig
  configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison
  configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison
  configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan
  docs/authors.rst
  docs/tasks/examples/bgc.png
Labels: clean up

#494 Allow main vs. ref comparision to use a cached main in addition to a cached ref analysis run
  config.example
  configs/acme1/config.20180129.DECKv1b_piControl.ne30_oEC.edison
  configs/alcf/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta
  configs/alcf/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta
  configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil
  configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl
  configs/edison/config.20180129.DECKv1b_piControl.ne30_oEC.edison
  configs/edison/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix
  configs/edison/config.20180514.G.oQU240wLI.edison
  configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison
  configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf
  configs/lanl/config.BGCphaeo4.testrun
  configs/lanl/config.GMPAS-OECO-ODMS-IAF.oRRS30to10v3
  configs/lanl/config.MatchBoth_orig
  configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison
  configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison
  configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan
  docs/config/runs.rst
  mpas_analysis/__main__.py
  mpas_analysis/config.default
  mpas_analysis/ocean/plot_climatology_map_subtask.py
Labels: bug, enhancement

#496 Change reference run to control run
  config.example
  configs/acme1/config.20180129.DECKv1b_piControl.ne30_oEC.edison
  configs/alcf/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta
  configs/alcf/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta
  configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil
  configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl
  configs/edison/config.20180129.DECKv1b_piControl.ne30_oEC.edison
  configs/edison/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix
  configs/edison/config.20180514.G.oQU240wLI.edison
  configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison
  configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf
  configs/lanl/config.BGCphaeo4.testrun
  configs/lanl/config.GMPAS-OECO-ODMS-IAF.oRRS30to10v3
  configs/lanl/config.MatchBoth_orig
  configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison
  configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison
  configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan
  docs/config/colormaps.rst
  docs/config/runs.rst
  mpas_analysis/__main__.py
  mpas_analysis/config.default
  mpas_analysis/ocean/climatology_map_antarctic_melt.py
  mpas_analysis/ocean/climatology_map_argo.py
  mpas_analysis/ocean/climatology_map_bgc.py
  mpas_analysis/ocean/climatology_map_eke.py
  mpas_analysis/ocean/climatology_map_mld.py
  mpas_analysis/ocean/climatology_map_ohc_anomaly.py
  mpas_analysis/ocean/climatology_map_schmidtko.py
  mpas_analysis/ocean/climatology_map_sose.py
  mpas_analysis/ocean/climatology_map_ssh.py
  mpas_analysis/ocean/climatology_map_sss.py
  mpas_analysis/ocean/climatology_map_sst.py
  mpas_analysis/ocean/geojson_transects.py
  mpas_analysis/ocean/index_nino34.py
  mpas_analysis/ocean/meridional_heat_transport.py
  mpas_analysis/ocean/plot_climatology_map_subtask.py
  mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py
  mpas_analysis/ocean/plot_transect_subtask.py
  mpas_analysis/ocean/sose_transects.py
  mpas_analysis/ocean/streamfunction_moc.py
  mpas_analysis/ocean/time_series_antarctic_melt.py
  mpas_analysis/ocean/time_series_ohc_anomaly.py
  mpas_analysis/ocean/time_series_sst.py
  mpas_analysis/ocean/woce_transects.py
  mpas_analysis/sea_ice/climatology_map_berg_conc.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
  mpas_analysis/sea_ice/plot_climatology_map_subtask.py
  mpas_analysis/sea_ice/time_series.py
  mpas_analysis/shared/html/pages.py
  mpas_analysis/shared/html/templates/component_page.html
  mpas_analysis/shared/html/templates/main_page.html
  mpas_analysis/shared/plot/plotting.py
Labels: clean up
