Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2018-07, with the labels that each got.

#443 Disable HDF5 locking in example job scripts
  configs/alcf/job_script.cooley.bash
  configs/anvil/job_script.anvil.bash
  configs/cori/job_script.cori-haswell.bash
  configs/cori/job_script.cori-knl.bash
  configs/edison/job_script.edison.bash
  configs/job_script.default.bash
  configs/lanl/job_script.lanl.bash
  configs/olcf/job_script.olcf.bash
Labels: bug, clean up

#439 Fix bug in interpolating transect segments
  mpas_analysis/ocean/compute_transects_subtask.py
Labels: bug

#320 Add iceberg concentration plots task
  docs/analysis_tasks.rst
  docs/api.rst
  docs/authors.rst
  docs/tasks/climatologyMapIcebergConcSH.rst
  docs/tasks/examples/berg_conc_sh.png
  mpas_analysis/config.default
  mpas_analysis/obs/observational_datasets.xml
  mpas_analysis/sea_ice/__init__.py
  mpas_analysis/sea_ice/climatology_map_berg_conc.py
  mpas_analysis/sea_ice/plot_climatology_map_subtask.py
  mpas_analysis/shared/grid/grid.py
  preprocess_observations/Altiberg_mergefiles.sh
  run_mpas_analysis
Labels: enhancement

#433 Add initial surface ocean BGC capability
  configs/lanl/config.BGCphaeo4.testrun
  configs/lanl/config.GMPAS-OECO-ODMS-IAF.oRRS30to10v3
  docs/authors.rst
  mpas_analysis/config.default
  mpas_analysis/obs/observational_datasets.xml
  mpas_analysis/ocean/__init__.py
  mpas_analysis/ocean/climatology_map_bgc.py
  preprocess_observations/preprocess_BGC_data.py
  run_mpas_analysis
Labels: enhancement
