Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2018-08, with the labels that each got.

#450 Transect contour plots
  mpas_analysis/config.default
  mpas_analysis/ocean/plot_transect_subtask.py
  mpas_analysis/shared/plot/plotting.py
Labels: enhancement

#449 Fix error reporting on tasks
  run_mpas_analysis
Labels: bug

#453 Refactor BGC so it is one task, not one per field
  configs/lanl/config.BGCphaeo4.testrun
  configs/lanl/config.GMPAS-OECO-ODMS-IAF.oRRS30to10v3
  mpas_analysis/config.default
  mpas_analysis/ocean/climatology_map_bgc.py
  run_mpas_analysis
Labels: clean up

#447 Eddy Kinetic Energy (EKE) climatology analysis
  .gitignore
  docs/analysis_tasks.rst
  docs/api.rst
  docs/design_docs.rst
  docs/design_docs/eddykineticenergy.md
  docs/tasks/climatologyMapEKE.rst
  docs/tasks/examples/eke.png
  mpas_analysis/config.default
  mpas_analysis/obs/analysis_input_files
  mpas_analysis/obs/observational_datasets.xml
  mpas_analysis/ocean/__init__.py
  mpas_analysis/ocean/climatology_map_eke.py
  mpas_analysis/ocean/plot_climatology_map_subtask.py
  run_mpas_analysis
Labels: enhancement

#454 Update observations XML for EKE
  mpas_analysis/obs/observational_datasets.xml
Labels: bug

#456 Update the list of public observations
  mpas_analysis/obs/analysis_input_files
  mpas_analysis/obs/observational_datasets.xml
  mpas_analysis/shared/io/download.py
Labels: bug, enhancement
