Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2019-03, with the labels that each got.

#548 Adding new config file for run on Cori-KNL.
  configs/cori/config.20190225.GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI.cori-knl
Labels: enhancement

#549 Fix lat/lon axis limits for WOCE with bounds
  mpas_analysis/shared/plot/plotting.py
Labels: bug

#547 Check for enough data in anomaly and Nino34 tasks; fix MOC time series with 1 year of data
  README.md
  mpas_analysis/__main__.py
  mpas_analysis/ocean/climatology_map_ohc_anomaly.py
  mpas_analysis/ocean/compute_anomaly_subtask.py
  mpas_analysis/ocean/index_nino34.py
  mpas_analysis/ocean/streamfunction_moc.py
Labels: bug

#551 Support multiple subprocesses per task (12 for ncclimo in bck mode)
  README.md
  ci/requirements.yml
  docs/conf.py
  docs/environment.yml
  mpas_analysis/__main__.py
  mpas_analysis/config.default
  mpas_analysis/shared/analysis_task.py
  mpas_analysis/shared/climatology/mpas_climatology_task.py
  mpas_analysis/shared/grid/grid.py
  mpas_analysis/shared/plot/plotting.py
  mpas_analysis/test/test_mpas_climatology_task.py
  mpas_analysis/test/test_mpas_climatology_task/config.QU240
  setup.py
Labels: enhancement

#552 Switch to conda-forge and mpas-analysis package in README
  README.md
Labels: clean up

#554 Remove proj4 requirement and constraint
  README.md
  ci/requirements.yml
  docs/environment.yml
Labels: clean up

#553 Optionally compute climatologies with xarray/dask
  configs/alcf/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta
  configs/alcf/config.20190301.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta
  configs/alcf/job_script.cooley.30to10.bash
  mpas_analysis/__main__.py
  mpas_analysis/ocean/climatology_map_ohc_anomaly.py
  mpas_analysis/ocean/meridional_heat_transport.py
  mpas_analysis/ocean/sose_transects.py
  mpas_analysis/ocean/streamfunction_moc.py
  mpas_analysis/shared/climatology/mpas_climatology_task.py
  mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
  mpas_analysis/test/test_mpas_climatology_task.py
Labels: enhancement

#555 Add support and docs for ncclimo "mpi" mode
  docs/config/execute.rst
  mpas_analysis/config.default
  mpas_analysis/shared/analysis_task.py
  mpas_analysis/shared/climatology/mpas_climatology_task.py
Labels: enhancement
