Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2019-07, with the labels that each got.

#597 Add support for SOSE maps on a 10,000 x 10,000 km grid
  docs/tasks/climatologyMapSose.rst
  mpas_analysis/__main__.py
  mpas_analysis/config.default
  mpas_analysis/obs/sose_10000km_input_files
  mpas_analysis/ocean/climatology_map_sose.py
  mpas_analysis/shared/io/download.py
  preprocess_observations/mds.py
  preprocess_observations/preprocess_SOSE_data.py
  setup.py
Labels: enhancement

#610 Isolate requests import
  README.md
  docs/api.rst
  download_analysis_data.py
  download_natural_earth_110m.py
  mpas_analysis/__main__.py
  mpas_analysis/download_data.py
  setup.py
Labels: clean up

#611 Round dlat/dlon in mesh names to 3 digits
  mpas_analysis/obs/analysis_input_files
  mpas_analysis/shared/grid/grid.py
Labels: clean up

#612 Add customDirectory for diagnostics
  docs/config/diagnostics.rst
  mpas_analysis/config.default
  mpas_analysis/ocean/ocean_regional_profiles.py
  mpas_analysis/ocean/streamfunction_moc.py
  mpas_analysis/ocean/time_series_antarctic_melt.py
  mpas_analysis/ocean/time_series_ocean_regions.py
  mpas_analysis/shared/climatology/climatology.py
  mpas_analysis/shared/io/utility.py
  mpas_analysis/shared/regions/compute_region_masks_subtask.py
  mpas_analysis/test/test_climatology.py
  mpas_analysis/test/test_mpas_climatology_task/config.QU240
  mpas_analysis/test/test_remap_obs_clim_subtask/config.remap_obs
Labels: bug, enhancement

#613 Add 'antarctic' and 'arctic' tags to tasks
  mpas_analysis/ocean/climatology_map_antarctic_melt.py
  mpas_analysis/ocean/climatology_map_schmidtko.py
  mpas_analysis/ocean/climatology_map_sose.py
  mpas_analysis/ocean/sose_transects.py
  mpas_analysis/ocean/time_series_antarctic_melt.py
  mpas_analysis/ocean/time_series_ocean_regions.py
  mpas_analysis/sea_ice/climatology_map_berg_conc.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
  mpas_analysis/sea_ice/time_series.py
Labels: clean up

#614 Add custom config file to webpage
  mpas_analysis/__main__.py
  mpas_analysis/shared/html/pages.py
  mpas_analysis/shared/html/templates/main_page.html
  mpas_analysis/shared/html/templates/style.css
Labels: enhancement

#615 Add missing config.html template
  mpas_analysis/shared/html/templates/config.html
Labels: bug

#618 Adds sample config and jobscript file for compy
  configs/compy/config.20190711.testLuke.A_WCYCL1850S.ne30_oECv3.compy
  configs/compy/job_script.compy.bash
Labels: enhancement, priority
