Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2020-08, with the labels that each got.

#720 Update documentation to describe possible customizations
  README.md
Labels: documenation

#722 Update docstrings to get rid of recent warnings
  docs/api.rst
  mpas_analysis/configuration/mpas_analysis_config_parser.py
  mpas_analysis/shared/climatology/climatology.py
  mpas_analysis/shared/time_series/time_series.py
Labels: documenation

#719 Add a tutorial for running analysis on a QU480 run
  config.example
  docs/index.rst
  docs/tutorials.rst
  docs/tutorials/getting_started.rst
  mpas_analysis/config.default
Labels: documenation, priority

#724 Fix --list flag
  mpas_analysis/ocean/streamfunction_moc.py
  mpas_analysis/ocean/time_series_ocean_regions.py
  mpas_analysis/ocean/time_series_transport.py
Labels: bug

#726 Fix how colormaps are plotted
  mpas_analysis/shared/plot/colormap.py
Labels: bug

#727 Add support for fewer than 12 ncclimo threads
  docs/config/execute.rst
  mpas_analysis/config.default
  mpas_analysis/shared/climatology/mpas_climatology_task.py
Labels: enhancement

#725 Fix race condition with melt tables
  mpas_analysis/ocean/climatology_map_antarctic_melt.py
Labels: bug

#728 Set up CI with Azure Pipelines
  README.md
  azure-pipelines.yml
  ci/environment-py36.yml
  ci/environment-py37-xarray-master.yml
  ci/environment-py37.yml
  ci/environment-py38.yml
  ci/install.bash
  ci/python3.6.yaml
  ci/python3.7.yaml
  ci/python3.8.yaml
  ci/recipe/meta.yaml
  ci/test_and_publish_docs.bash
Labels: documenation, in progress
