Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2022-10, with the labels that each got.

#918 Fixes to formatting and config options for climatologyMapBSF
  mpas_analysis/default.cfg
  mpas_analysis/ocean/climatology_map_bsf.py
  mpas_analysis/ocean/regional_ts_diagrams.py
  mpas_analysis/ocean/time_series_ocean_regions.py
  mpas_analysis/shared/plot/climatology_map.py
Labels: bug

#915 Switch to plotting sea-ice concentration and thickness on projection grids
  docs/developers_guide/api.rst
  mpas_analysis/__main__.py
  mpas_analysis/default.cfg
  mpas_analysis/ocean/climatology_map_antarctic_melt.py
  mpas_analysis/ocean/climatology_map_argo.py
  mpas_analysis/ocean/climatology_map_bgc.py
  mpas_analysis/ocean/climatology_map_bsf.py
  mpas_analysis/ocean/climatology_map_eke.py
  mpas_analysis/ocean/climatology_map_mld.py
  mpas_analysis/ocean/climatology_map_mld_min_max.py
  mpas_analysis/ocean/climatology_map_ohc_anomaly.py
  mpas_analysis/ocean/climatology_map_schmidtko.py
  mpas_analysis/ocean/climatology_map_sose.py
  mpas_analysis/ocean/climatology_map_ssh.py
  mpas_analysis/ocean/climatology_map_sss.py
  mpas_analysis/ocean/climatology_map_sst.py
  mpas_analysis/ocean/climatology_map_woa.py
  mpas_analysis/ocean/utility.py
  mpas_analysis/polar_regions.cfg
  mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
  mpas_analysis/shared/climatology/comparison_descriptors.py
  mpas_analysis/shared/plot/__init__.py
  mpas_analysis/shared/plot/climatology_map.py
  mpas_analysis/shared/plot/oned.py
  mpas_analysis/shared/plot/plot_climatology_map_subtask.py
  mpas_analysis/shared/plot/time_series.py
  mpas_analysis/shared/plot/vertical_section.py
  mpas_analysis/shared/projection/__init__.py
Labels: enhancement

#907 Add sea ice production/melting analysis tasks
  mpas_analysis/__main__.py
  mpas_analysis/default.cfg
  mpas_analysis/obs/observational_datasets.xml
  mpas_analysis/sea_ice/__init__.py
  mpas_analysis/sea_ice/climatology_map_melting.py
  mpas_analysis/sea_ice/climatology_map_production.py
Labels: enhancement

#919 Fix some docstrings
  mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
  mpas_analysis/shared/projection/__init__.py
Labels: documenation

#920 Add docs and examples for sea ice production tasks
  docs/users_guide/analysis_tasks.rst
  docs/users_guide/tasks/climatologyMapSeaIceMeltingNH.rst
  docs/users_guide/tasks/climatologyMapSeaIceMeltingSH.rst
  docs/users_guide/tasks/climatologyMapSeaIceProductionNH.rst
  docs/users_guide/tasks/climatologyMapSeaIceProductionSH.rst
  docs/users_guide/tasks/examples/ice_melting_nh.png
  docs/users_guide/tasks/examples/ice_melting_sh.png
  docs/users_guide/tasks/examples/ice_production_nh.png
  docs/users_guide/tasks/examples/ice_production_sh.png
Labels: documenation

#921 Fix description of building the docs
  README.md
Labels: documenation

#917 Add histogram plot type and ocean histogram task
  docs/users_guide/analysis_tasks.rst
  docs/users_guide/config/regions.rst
  docs/users_guide/tasks/examples/histogram_ssh_aviso_atl.png
  docs/users_guide/tasks/oceanHistogram.rst
  mpas_analysis/__main__.py
  mpas_analysis/default.cfg
  mpas_analysis/ocean/__init__.py
  mpas_analysis/ocean/histogram.py
  mpas_analysis/shared/plot/__init__.py
  mpas_analysis/shared/plot/histogram.py
Labels: enhancement

#923 Fixup formatting in histogram documentation
  docs/users_guide/tasks/oceanHistogram.rst
Labels: clean up, documenation
