Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2022-09, with the labels that each got.

#889 Switch to `noleap` instead of `gregorian_noleap`
  mpas_analysis/ocean/index_nino34.py
  mpas_analysis/sea_ice/time_series.py
  mpas_analysis/shared/climatology/climatology.py
  mpas_analysis/shared/generalized_reader/generalized_reader.py
  mpas_analysis/shared/io/mpas_reader.py
  mpas_analysis/shared/io/namelist_streams_interface.py
  mpas_analysis/shared/mpas_xarray/mpas_xarray.py
  mpas_analysis/shared/time_series/time_series.py
  mpas_analysis/shared/timekeeping/MpasRelativeDelta.py
  mpas_analysis/shared/timekeeping/utility.py
  mpas_analysis/test/test_climatology.py
  mpas_analysis/test/test_generalized_reader.py
  mpas_analysis/test/test_mpas_climatology_task/mpas-o_in
  mpas_analysis/test/test_mpas_xarray.py
  mpas_analysis/test/test_namelist_streams_interface.py
  mpas_analysis/test/test_namelist_streams_interface/namelist.ocean
  mpas_analysis/test/test_open_mpas_dataset.py
  mpas_analysis/test/test_remap_obs_clim_subtask/mpas-o_in
  mpas_analysis/test/test_timekeeping.py
Labels: bug, priority

#892 Improve error message on incorrect machine
  mpas_analysis/__main__.py
Labels: clean up

#894 Clean up ``ClimatologyMapOHCAnomaly``
  mpas_analysis/ocean/climatology_map_ohc_anomaly.py
Labels: clean up

#886 Update postprocessed MOC to match analysis member
  mpas_analysis/ocean/streamfunction_moc.py
Labels: enhancement

#901 Add missing var when continuing MOC calculation
  mpas_analysis/ocean/streamfunction_moc.py
Labels: bug

#902 Make sure both CI and develoment environments don't include conda MPI
  ci/recipe/meta.yaml
  dev-spec.txt
  suite/job_script.bash
  suite/setup.py
Labels: bug

#900 Fix hovmoller plot comparison
  mpas_analysis/ocean/plot_hovmoller_subtask.py
Labels: bug

#903 Fix generate command-line flag
  mpas_analysis/__main__.py
Labels: bug

#904 Don't decode time as part of transect remapping
  mpas_analysis/ocean/compute_transects_subtask.py
Labels: bug

#905 Fix `--list` when trying to write geojson files
  mpas_analysis/ocean/regional_ts_diagrams.py
  mpas_analysis/ocean/time_series_ocean_regions.py
Labels: bug

#895 Add 3 tutorials for developers
  docs/index.rst
  docs/tutorials/dev_add_task.rst
  docs/tutorials/dev_getting_started.rst
  docs/tutorials/dev_understand_a_task.rst
  docs/tutorials/getting_started.rst
  docs/tutorials/images/bsf.png
Labels: enhancement, documenation

#908 Add a check for duplicate analysis tasks and subtasks
  mpas_analysis/__main__.py
  mpas_analysis/shared/analysis_task.py
Labels: enhancement

#906 Add support for remapping from MPAS vertices
  mpas_analysis/shared/climatology/climatology.py
  mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
Labels: enhancement

#913 Fix config file on the webpage
  mpas_analysis/__main__.py
  mpas_analysis/shared/html/pages.py
Labels: bug

#914 Switch to using mamba and mambabuild in Azure
  azure-pipelines.yml
Labels: enhancement

#896 Add Arctic Ocean time series, profiles, and TS diagrams to polar regions
  mpas_analysis/default.cfg
  mpas_analysis/ocean/regional_ts_diagrams.py
  mpas_analysis/ocean/time_series_ocean_regions.py
  mpas_analysis/polar_regions.cfg
Labels: enhancement

#898 Add Horizontal Streamfunction plots + Subpolar North Atlantic projection
  mpas_analysis/__main__.py
  mpas_analysis/default.cfg
  mpas_analysis/ocean/__init__.py
  mpas_analysis/ocean/climatology_map_bsf.py
  mpas_analysis/ocean/plot_climatology_map_subtask.py
  mpas_analysis/polar_regions.cfg
  mpas_analysis/shared/climatology/comparison_descriptors.py
  mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
  mpas_analysis/shared/plot/climatology_map.py
  mpas_analysis/shared/plot/colormap.py
  mpas_analysis/shared/projection/__init__.py
Labels: enhancement
