Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2024-11, with the labels that each got.

#1032 Switch from WOA18 to WOA23
  docs/users_guide/tasks/climatologyMapWoa.rst
  docs/users_guide/tasks/regionalTSDiagrams.rst
  docs/users_guide/tasks/timeSeriesOceanRegions.rst
  mpas_analysis/default.cfg
  mpas_analysis/obs/observational_datasets.xml
  mpas_analysis/ocean/climatology_map_woa.py
  mpas_analysis/ocean/regional_ts_diagrams.py
  mpas_analysis/ocean/time_series_ocean_regions.py
  mpas_analysis/polar_regions.cfg
  mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py
  preprocess_observations/preprocess_woa23.py
Labels: enhancement

#1031 Fix land ice frazil in ocean conservation task
  mpas_analysis/ocean/conservation.py
Labels: bug

#1035 Remove the comparison grid name from sea ice gallery groups
  mpas_analysis/sea_ice/climatology_map_berg_conc.py
  mpas_analysis/sea_ice/climatology_map_melting.py
  mpas_analysis/sea_ice/climatology_map_production.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
  mpas_analysis/shared/plot/plot_climatology_map_subtask.py
Labels: clean up

#1037 Antarctic transects
  docs/users_guide/analysis_tasks.rst
  docs/users_guide/tasks/antshipTransects.rst
  docs/users_guide/tasks/examples/antship_transect.png
  mpas_analysis/__main__.py
  mpas_analysis/default.cfg
  mpas_analysis/obs/observational_datasets.xml
  mpas_analysis/ocean/__init__.py
  mpas_analysis/ocean/antship_transects.py
  mpas_analysis/polar_regions.cfg
  mpas_analysis/shared/plot/vertical_section.py
Labels: enhancement

#1039 Rename Greenland Regions --> ISMIP6 Greenland Regions
  ci/recipe/meta.yaml
  dev-spec.txt
  docs/conf.py
  docs/users_guide/config/regions.rst
  mpas_analysis/default.cfg
  mpas_analysis/polar_regions.cfg
Labels: clean up

#1041 Add python 3.13
  .github/workflows/build_workflow.yml
  ci/python3.13.yaml
  docs/tutorials/getting_started.rst
  setup.py
Labels: documenation

#1034 Add OHC anomaly to `timeSeriesOceanRegions`
  docs/users_guide/tasks/timeSeriesOceanRegions.rst
  mpas_analysis/default.cfg
  mpas_analysis/ocean/time_series_ocean_regions.py
Labels: enhancement
