Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2025-04, with the labels that each got.

#1080 Alternative xarray approach to computing convservation time series
  mpas_analysis/ocean/conservation.py
Labels: bug

#1081 Separate dependencies in `pyproject.toml`
  dev-spec.txt
  pyproject.toml
Labels: clean up, dependencies

#1064 Add support for custom climatology maps
  docs/developers_guide/api.rst
  docs/users_guide/analysis_tasks.rst
  docs/users_guide/tasks/climatologyMapCustom.rst
  docs/users_guide/tasks/examples/clim_map_custom.png
  mpas_analysis/__main__.py
  mpas_analysis/default.cfg
  mpas_analysis/ocean/__init__.py
  mpas_analysis/ocean/climatology_map_custom.py
  mpas_analysis/ocean/remap_depth_slices_subtask.py
  mpas_analysis/ocean/utility.py
Labels: enhancement

#1084 Fix conservation when list of inputs is empty
  mpas_analysis/ocean/conservation.py
Labels: bug

#1079 Check that all BSF projections are present
  mpas_analysis/ocean/climatology_map_bsf.py
Labels: bug

#1083 Set under/over indices for sea ice conc and thickness
  docs/users_guide/tasks/climatologyMapSeaIceConcNH.rst
  docs/users_guide/tasks/climatologyMapSeaIceConcSH.rst
  docs/users_guide/tasks/climatologyMapSeaIceThickNH.rst
  docs/users_guide/tasks/climatologyMapSeaIceThickSH.rst
  mpas_analysis/default.cfg
  mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
Labels: bug

#1085 Update to mpas tools 1.0.0 and pyremap 2.0.0
  README.md
  ci/recipe/meta.yaml
  configs/alcf/job_script.cooley.bash
  configs/compy/job_script.compy.bash
  configs/job_script.default.bash
  configs/lanl/job_script.lanl.bash
  configs/lcrc/job_script.anvil.bash
  configs/lcrc/job_script.chrysalis.bash
  configs/nersc/job_script.cori-haswell.bash
  configs/nersc/job_script.cori-knl.bash
  configs/nersc/job_script.pm-cpu.bash
  configs/olcf/job_script.olcf.bash
  dev-spec.txt
  docs/tutorials/dev_add_task.rst
  docs/tutorials/dev_getting_started.rst
  mpas_analysis/ocean/climatology_map_antarctic_melt.py
  mpas_analysis/ocean/climatology_map_argo.py
  mpas_analysis/ocean/climatology_map_bgc.py
  mpas_analysis/ocean/climatology_map_eke.py
  mpas_analysis/ocean/climatology_map_mld.py
  mpas_analysis/ocean/climatology_map_schmidtko.py
  mpas_analysis/ocean/climatology_map_ssh.py
  mpas_analysis/ocean/climatology_map_sss.py
  mpas_analysis/ocean/climatology_map_sst.py
  mpas_analysis/ocean/climatology_map_waves.py
  mpas_analysis/ocean/climatology_map_woa.py
  mpas_analysis/ocean/compute_transects_subtask.py
  mpas_analysis/ocean/plot_transect_subtask.py
  mpas_analysis/ocean/remap_sose_climatology.py
  mpas_analysis/sea_ice/climatology_map_berg_conc.py
  mpas_analysis/sea_ice/climatology_map_melting.py
  mpas_analysis/sea_ice/climatology_map_production.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py
  mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
  mpas_analysis/shared/climatology/climatology.py
  mpas_analysis/shared/climatology/mpas_climatology_task.py
  mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
  mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py
  mpas_analysis/shared/plot/plot_climatology_map_subtask.py
  mpas_analysis/shared/plot/vertical_section.py
  mpas_analysis/test/test_climatology.py
  mpas_analysis/test/test_remap_obs_clim_subtask.py
  mpas_analysis/test/test_remap_obs_clim_subtask/remap_mld_obs.py
  preprocess_observations/preprocess_SOSE_data.py
  preprocess_observations/preprocess_Schmidtko_data.py
  preprocess_observations/preprocess_adusumilli_melt.py
  preprocess_observations/preprocess_paolo_melt.py
  preprocess_observations/remap_rignot.py
  suite/run_dev_suite.bash
Labels: enhancement, clean up, dependencies

#1086 Fix hangs in ocean conservation
  mpas_analysis/ocean/conservation.py
Labels: bug

#1074 Switch to using barotropic streamfunction from `mpas_tools`
  ci/recipe/meta.yaml
  dev-spec.txt
  mpas_analysis/ocean/climatology_map_bsf.py
Labels: bug

#1087 Reserve all processes for BSF calculation
  mpas_analysis/ocean/climatology_map_bsf.py
Labels: performance

#1089 Expand variables for polar regions conservation and mass fluxes
  mpas_analysis/ocean/conservation.py
  mpas_analysis/polar_regions.cfg
Labels: enhancement

#1091 Switch CI from miniconda to micromamba
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
Labels: ci

#1092 Add netcdf support to geojson transects
  docs/developers_guide/api.rst
  docs/users_guide/analysis_tasks.rst
  docs/users_guide/tasks/geojsonNetcdfTransects.rst
  docs/users_guide/tasks/geojsonTransects.rst
  mpas_analysis/__main__.py
  mpas_analysis/default.cfg
  mpas_analysis/ocean/__init__.py
  mpas_analysis/ocean/compute_transects_subtask.py
  mpas_analysis/ocean/geojson_netcdf_transects.py
  mpas_analysis/ocean/geojson_transects.py
Labels: enhancement

#1093 Transpose transect obs dims to match model dims
  mpas_analysis/ocean/plot_transect_subtask.py
Labels: bug
