Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2025-01, with the labels that each got.

#1047 More fixes following move to `pyproject.toml`
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
  MANIFEST.in
  ci/recipe/meta.yaml
  dev-spec.txt
  docs/conf.py
  mpas_analysis/__init__.py
  mpas_analysis/__main__.py
  mpas_analysis/shared/html/pages.py
  mpas_analysis/version.py
  pyproject.toml
Labels: bug, clean up

#1048 Relax upper bound on ESMF
  ci/recipe/meta.yaml
  dev-spec.txt
Labels: dependencies

#1049 Use separate conda cache directories in CI
  .github/workflows/build_workflow.yml
Labels: ci

#1050 Fix barotropic streamfuncion
  mpas_analysis/shared/plot/climatology_map.py
Labels: bug

#899 Add osnap T S climtransects
  docs/users_guide/analysis_tasks.rst
  docs/users_guide/tasks/examples/osnap_transect.png
  docs/users_guide/tasks/osnapTransects.rst
  mpas_analysis/__main__.py
  mpas_analysis/default.cfg
  mpas_analysis/obs/observational_datasets.xml
  mpas_analysis/ocean/__init__.py
  mpas_analysis/ocean/osnap_transects.py
  preprocess_observations/preprocessingOSNAP30day.ipynb
Labels: enhancement

#1054 Fix several errors in the docs
  docs/tutorials/dev_getting_started.rst
  docs/users_guide/tasks/antshipTransects.rst
  docs/users_guide/tasks/climatologyMapSeaIceAlbedoNH.rst
  docs/users_guide/tasks/climatologyMapSeaIceVolumeTendencyThermoNH.rst
  docs/users_guide/tasks/climatologyMapSeaIceVolumeTendencyThermoSH.rst
  docs/users_guide/tasks/climatologyMapSeaIceVolumeTendencyTranspNH.rst
  docs/users_guide/tasks/climatologyMapSeaIceVolumeTendencyTranspSH.rst
  docs/users_guide/tasks/osnapTransects.rst
  mpas_analysis/obs/observational_datasets.xml
Labels: clean up, documenation
