Repository MPAS-Dev/MPAS-Analysis, pull requests merged in 2025-03, with the labels that each got.

#1070 Set `decode_timedelta=False` to avoid future warnings in `xarray.open_dataset()` calls
  mpas_analysis/ocean/conservation.py
  mpas_analysis/ocean/meridional_heat_transport.py
  mpas_analysis/shared/climatology/mpas_climatology_task.py
  mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
  mpas_analysis/shared/time_series/mpas_time_series_task.py
  mpas_analysis/shared/time_series/time_series.py
Labels: clean up

#1071 Add FRIS comparison grid
  mpas_analysis/default.cfg
  mpas_analysis/shared/climatology/comparison_descriptors.py
  mpas_analysis/shared/projection/__init__.py
  suite/template.cfg
Labels: enhancement

#1072 Fix inset bounds
  mpas_analysis/shared/plot/inset.py
Labels: bug

#1069 Fix barotropic streamfunction calculation
  docs/users_guide/tasks/climatologyMapBSF.rst
  docs/users_guide/tasks/examples/bsf.png
  mpas_analysis/default.cfg
  mpas_analysis/ocean/climatology_map_bsf.py
  mpas_analysis/polar_regions.cfg
  mpas_analysis/shared/climatology/comparison_descriptors.py
  mpas_analysis/shared/plot/SciVisColorColormaps/__init__.py
  mpas_analysis/shared/plot/SciVisColorCustom/3wave-blue-red-brown.xml
  mpas_analysis/shared/plot/SciVisColorCustom/3wave-green-red-purple.xml
  mpas_analysis/shared/plot/SciVisColorCustom/__init__.py
  mpas_analysis/shared/plot/SciVisColorCustom/div-one-third-blue-two-thirds-red.xml
  mpas_analysis/shared/plot/SciVisColorCustom/div-one-third-green-two-thirds-red.xml
  mpas_analysis/shared/plot/ScientificColourMaps7/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/acton/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/bam/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/bamO/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/bamako/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/batlow/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/batlowK/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/batlowW/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/berlin/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/bilbao/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/broc/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/brocO/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/buda/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/bukavu/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/cork/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/corkO/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/davos/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/devon/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/fes/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/grayC/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/hawaii/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/imola/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/lajolla/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/lapaz/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/lisbon/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/nuuk/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/oleron/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/oslo/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/roma/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/romaO/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/tofino/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/tokyo/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/turku/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/vanimo/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/vik/__init__.py
  mpas_analysis/shared/plot/ScientificColourMaps7/vikO/__init__.py
  mpas_analysis/shared/plot/climatology_map.py
  mpas_analysis/shared/plot/colormap.py
  mpas_analysis/shared/plot/plot_climatology_map_subtask.py
  mpas_analysis/shared/plot/vertical_section.py
  mpas_analysis/shared/projection/__init__.py
Labels: bug

#1073 Update Arctic and add North Atlantic BSF config options
  mpas_analysis/polar_regions.cfg
Labels: enhancement

#1076 Add missing colormaps
  MANIFEST.in
  ci/recipe/meta.yaml
Labels: bug
